DROP TABLE IF EXISTS Employee;

CREATE TABLE Employee (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  department VARCHAR(250) NOT NULL,
  CREATED_AT TIMESTAMP,
  LAST_MODIFIED_AT TIMESTAMP
);

INSERT INTO Employee (name, department, CREATED_AT, LAST_MODIFIED_AT) VALUES
  ('Aishwarya', 'HR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Pranit', 'TECHNOLOGY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Swarad', 'MANAGEMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Prajakta', 'SALES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Aalok', 'MANAGEMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);